### ISSUE TITLE
Db ornek veriler ile dolduralacak

### ISSUE THREAD

**Issue by faotomasyon** [faotomasyon/faotomation#10]
@furkanaygur tarafindan db test verileri ile doldurulacak.

**Comment by furkanaygur** [comment]
Faker kutuphanesi kullanilarak db'ye test user'lar eklendi

**Comment by furkanaygur** [comment]
ilgili task'in commit linki : https://github.com/faotomasyon/faotomation/commit/0f4d6c043f5f230aca344e64b75c19697eee7d4f
