### ISSUE TITLE
Middleware eklenecek

### ISSUE THREAD

**Issue by faotomasyon** [faotomasyon/faotomation#11]
@furkanaygur tarafindan middleware eklenecek

**Comment by furkanaygur** [comment]
middleware dosyasi eklendi. Middleware in yaptigi islemler controller dosyalarindan kaldirildi.

**Comment by furkanaygur** [comment]
ilgili task'in commit linki : https://github.com/faotomasyon/faotomation/commit/5bcdb8baee9ba4223018be7cb902f3c192e16ded
