### ISSUE TITLE
User(Player) islemleri icin endpoint'ler yazilacak

### ISSUE THREAD

**Issue by faotomasyon** [faotomasyon/faotomation#12]
@furkanaygur tarafindan player CRUD islemleri icin endpoint'ler yazilacak

**Comment by furkanaygur** [comment]
User(Player) icin CRUD islemlerini yapan endpoint'ler yazildi.

**Comment by furkanaygur** [comment]
ilgili task'in commit linki : https://github.com/faotomasyon/faotomation/commit/3b2543ecd022b7fe1f486ac280bb1010f81ab1bd
