### ISSUE TITLE
seeder.php script'i guncellenecek yeni veriler eklenecek

### ISSUE THREAD

**Issue by faotomasyon** [faotomasyon/faotomation#13]
@furkanaygur tarafindan seeder.php script'i guncellenecek ve   yeni veriler eklenecek.

**Comment by furkanaygur** [comment]
seeder.php script'i  yeni kayitlar ekene guncellendi.

**Comment by furkanaygur** [comment]
ilgili task'in commit linki : https://github.com/faotomasyon/faotomation/commit/9b6d59840fd3ed5e344a685d47cbcebfcfd12b06
