### ISSUE TITLE
Web Antrenörler sayfasi yapilacak

### ISSUE THREAD

**Issue by faotomasyon** [faotomasyon/faotomation#17]
@Ayseekinci tarafindan web coaches sayfasi yapilacak. Figma uzerinden tasarlanacak ve html css'e dokulecek

**Comment by furkanaygur** [comment]
Commit review edildi.
Commit linki : https://github.com/faotomasyon/faotomation/commit/b7c8fead0cafe37f01647a56dbee48a6050998da#diff-4b5e57f6eb2f42b9039b3d1e13929295f231749c510cbe341cd68036d9af97e2
