### ISSUE TITLE
Coach islemleri icin endpoint'ler yazilacak

### ISSUE THREAD

**Issue by faotomasyon** [faotomasyon/faotomation#21]
@furkanaygur tarafindan coach CRUD islemleri icin endpoint'ler yazilacak.

**Comment by furkanaygur** [comment]
Coaches icin CRUD islemlerini yapan endpoint'ler yazildi.

**Comment by furkanaygur** [comment]
ilgili task'in commit linki : https://github.com/faotomasyon/faotomation/commit/4bebb9420e97b548004672a2e14bb9abd00f45eb
