### ISSUE TITLE
Repo'ya readme dosyasi eklenecek ve duzenlenecek

### ISSUE THREAD

**Issue by faotomasyon** [faotomasyon/faotomation#23]
@furkanaygur tarafindan readme dosyasi eklenecek ve duzenlenecek

**Comment by furkanaygur** [comment]
API için readme dosyası eklendi.

**Comment by furkanaygur** [comment]
ilgili task'in commit linki : https://github.com/faotomasyon/faotomation/commit/4301396e9daff5cbf9e875e4e9ebb8d562e9fa9e
