### ISSUE TITLE
Figma uzerinden yapilan tasarimlarda duzenlemeler yapmak uzere toplanti yapilacak

### ISSUE THREAD

**Issue by faotomasyon** [faotomasyon/faotomation#30]
Tum ekip uyelerinin katildigi ve tasarimlarda yapilacak iyilestirmeler hakkinda bir toplanti yapilacak.

**Comment by furkanaygur** [comment]
Ekipçe tasarımlar hakkında konuşuldu. İyileştirmeler yapıldı. Bulunduğumuz nokta hakkında fikir alışverişi yapıldı.
