### ISSUE TITLE
Web Sifremi Unuttum Figma tasarımı

### ISSUE THREAD

**Issue by faotomasyon** [faotomasyon/faotomation#31]
@Ayseekinci tarafından figma üzerinden tasarım yapılacak.

**Comment by furkanaygur** [comment]
Figma tasarimi ve kodlari incelendi.
Figma Linki: https://www.figma.com/file/0iUvwKDrOjjw4IZO9dnC8E/%C5%9Eifremi-unutum-Ekran%C4%B1?node-id=0%3A1
