### ISSUE TITLE
Mobil Register Ekranı yapılacak

### ISSUE THREAD

**Issue by sindaakyil** [faotomasyon/faotomation#34]

**Comment by furkanaygur** [comment]
Commit review edildi.
Commit linki : https://github.com/faotomasyon/faotomation/commit/529f9d9488d22dc79b004de146de003f43253df4

**Comment by furkanaygur** [comment]
Commit review edildi.
Commit linki : https://github.com/faotomasyon/faotomation/commit/574bd35c603abba95a0dd088acb222c55d1dc4e0
