### ISSUE TITLE
Web Futbolcular sayfasi yapilacak

### ISSUE THREAD

**Issue by faotomasyon** [faotomasyon/faotomation#44]
@Ayseekinci tarafindan web oyuncular sayfasi yapilacak. Figma uzerinden tasarlanacak ve html css'e dokulecek

**Comment by furkanaygur** [comment]
Commit review edildi.
Commit linki : https://github.com/faotomasyon/faotomation/commit/aa2a7b0b26b62cc292ef198fa715ba57d184a93c
