### ISSUE TITLE
Jobs islemleri icin endpoint'ler yazilacak.

### ISSUE THREAD

**Issue by faotomasyon** [faotomasyon/faotomation#50]
@furkanaygur tarafindan jobs CRUD islemleri icin endpoint'ler yazilacak.

**Comment by furkanaygur** [comment]
Jobs icin CRUD islemlerini yapan endpoint'ler yazildi.
Commit linki : https://github.com/faotomasyon/faotomation/commit/dc4791f614d7bf7690ff5590367dda4a7118fac9
