### ISSUE TITLE
Figma ile mobil tasarim yapilacak

### ISSUE THREAD

**Issue by faotomasyon** [faotomasyon/faotomation#7]
@sindaakyil tarafindan figma kullanilarak mobil uygulamanin tasarimi yapilacak

**Comment by furkanaygur** [comment]
Figma uzerinden yapilan tasarim incelendi.
Tasarim Linki : https://www.figma.com/file/3cF3yOJWIi9Enp4NyJJhXn/Untitled?node-id=0%3A1
