### ISSUE TITLE
Login icin endpoint eklenecek

### ISSUE THREAD

**Issue by faotomasyon** [faotomasyon/faotomation#8]
@furkanaygur tarafindan login icin endpoint eklenecek

**Comment by furkanaygur** [comment]
Login ve logout endpointleri eklendi.

**Comment by furkanaygur** [comment]
ilgili task'in commit linki : https://github.com/faotomasyon/faotomation/commit/ecb5a35a9b72ad4b083910c40739633e608bf6ba
