### ISSUE TITLE
DB tablolari olusturulacak ve migrate.php dosyasina eklenecek

### ISSUE THREAD

**Issue by faotomasyon** [faotomasyon/faotomation#9]
@furkanaygur tarafindan db tablolari olusturulacak ve create table sorgulari migrate.php dosyasina eklenecek

**Comment by furkanaygur** [comment]
Migrate php ve tablolari eklemek icin gerekli sorgular eklendi

**Comment by furkanaygur** [comment]
ilgili task'in commit linki : https://github.com/faotomasyon/faotomation/commit/f76bb3c8eeedbaebe771b6856f8cec24877aa856
